### ISSUE TITLE
Can't get streaming from Gmusic to Echo?!

### ISSUE THREAD

**Issue by 2themaxx** [stevenleeg/geemusic#92] opened 2017-04-28 04:46 UTC
I'm at my wit's end here. I've followed all the instructions to get a Heroku account set up. I'm getting responses from the server, both in test, and verbally from my echo and they show up in the logs with Heroku CLI. However no music ever plays. I have a Google Music subscription, and I'm just trying to play songs/albums that are in the Google music library. The service request response is giving valid Thumbnail art, and after adding a debug logger for the original "api.get_google_stream_url" (and a few rounds of autopep8), I verified I'm getting valid URLs from Google Music that play in my browser. However the thumbnail doesn't show up in the Alexa webapp, nor do I hear music from my speaker.... I've quadruple checked my App_url and there's no trailing slash or "/alexa" at the end.

help!!!!

The service request to "Play Gangnam Style":
{
  "session": {
    "sessionId": "SessionId.1d691ed1-3fea-4177-9d71-29c7e2990339",
    "application": {
      "applicationId": "amzn1.ask.skill.baef-9358-42d4-9638-684560edd172"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.4RPNWDMSKOW66ZNT5RB3PL33DEDOZLSS27OHMLGB5ZDQUYT37ZORHWA36UZ2TCVW5MLGKGEQIH3JMOWAH3AXIXNWRTGQ65EEHFS5NNZCHWAZCHTD7XROCO4N2PNSBFAY67AS5U2KKCD3LARRMFV5V7Q7U4IDCHQRWHM7LS7A2K54PWOWZQ7OFVGJTLIQ77J2RM6JNBYV7GI"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.8361ce22-4c0b-4f17-9435-a7dd785dddf0",
    "locale": "en-US",
    "timestamp": "2017-04-28T04:32:07Z",
    "intent": {
      "name": "GeeMusicPlaySongIntent",
      "slots": {
        "artist_name": {
          "name": "artist_name"
        },
        "song_name": {
          "name": "song_name",
          "value": "Gangnam style"
        }
      }
    }
  },
  "version": "1.0"
}

And the Response from Alexa:
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Playing Gangnam Style by Psy"
    },
    "card": {
      "text": "",
      "title": "Playing Gangnam Style by Psy",
      "image": {
        "smallImageUrl": "https://lh3.ggpht.com/0v0R_euthsqJUci7kLG2OmJAug9d8MLqnTGZCmXuyNck-lR9N2h-PoKy5Fune_mQRiGuTyb2udU",
        "largeImageUrl": "https://lh3.ggpht.com/0v0R_euthsqJUci7kLG2OmJAug9d8MLqnTGZCmXuyNck-lR9N2h-PoKy5Fune_mQRiGuTyb2udU"
      },
      "type": "Standard"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}

Am I missing something here?

**Comment by 2themaxx** [comment] 2017-04-30 22:57
Just wanted to clarify I also double-checked the SSL certificate type on the alexa skill side, and it is correct according to the Heroku instructions.

**Comment by rosahas** [comment] 2017-05-03 01:10
I have a similar problem.. can't figure out what the issue is yet.  The log on Heruko doesn't seem to share much.  @2themaxx have you checked the Heruko log?

**Comment by 2themaxx** [comment] 2017-05-07 01:12
@rosahas: Yes, I checked the heroku logs, I first modified the geemusic python files to log the URL before it gets translated to Alexa, which is how I know it's resolving the request to a playable URL.  If I paste the URL from the Heroku logs into a browser (such as chrome), it plays the requested song from Gmusic. I've tried with Bullet with Butterfly wings (availble on Amazon prime music as well), Gangnam style (only available as a clip from Prime music). Neither one plays when asking Geemusic to replay, although it gets the proper urls for MP3 and for Album art.....

**Comment by 2themaxx** [comment] 2017-05-07 18:12
So, I turned on Debug logging for Flask-Ask (in "server.py") and here are the log results from two requests from the heroku logs. It appears that I'm getting a "Media_Error_Invalid_Request" from Alexa. I'm not sure why, but the "googleusercontent" link is valid (when pasted into a browser), but apparently by the time it gets sent to Alexa, something is wrong with the link (or something isn't being translated properly). Any help would be appreciated! (please note I've changed the alexaid/deviceids/HerokuURL so those links won't work directly, but otherwise the logs are the same.

2017-05-07T17:43:26.209298+00:00 app[web.1]:       "message": "Not Found, Response Code:404",
2017-05-07T17:43:26.209299+00:00 app[web.1]:       "type": "MEDIA_ERROR_INVALID_REQUEST"
2017-05-07T17:43:26.209299+00:00 app[web.1]:     },
2017-05-07T17:43:26.209300+00:00 app[web.1]:     "locale": "en-US",
2017-05-07T17:43:26.209301+00:00 app[web.1]:     "requestId": "amzn1.echo-api.request.d2d5c8c9-bce6-494d-84fa-364a085f5528",
2017-05-07T17:43:26.209301+00:00 app[web.1]:     "timestamp": "2017-05-07T17:43:26Z",
2017-05-07T17:43:26.209302+00:00 app[web.1]:     "token": "33826",
2017-05-07T17:43:26.209302+00:00 app[web.1]:     "type": "AudioPlayer.PlaybackFailed"
2017-05-07T17:43:26.209303+00:00 app[web.1]:   },
2017-05-07T17:43:26.209304+00:00 app[web.1]:   "version": "1.0"
2017-05-07T17:43:26.209308+00:00 app[web.1]: }
2017-05-07T17:43:26.209890+00:00 app[web.1]: {
2017-05-07T17:43:26.209892+00:00 app[web.1]:   "offsetInMilliseconds": 0,
2017-05-07T17:43:26.209893+00:00 app[web.1]:   "playerActivity": "STOPPED",
2017-05-07T17:43:26.209893+00:00 app[web.1]:   "token": "33826",
2017-05-07T17:43:26.209894+00:00 app[web.1]:   "url": "https://ccgmusic.herokuapp.com/alexa/stream/Tgmrl6gfrlrvta4jriy4qsm5jue"
2017-05-07T17:43:26.209895+00:00 app[web.1]: }
2017-05-07T17:43:26.210543+00:00 app[web.1]: 10.152.65.114 - - [07/May/2017 17:43:26] "POST /alexa HTTP/1.1" 400 -
2017-05-07T17:43:57.400843+00:00 app[web.1]:   "context": {
2017-05-07T17:43:57.400826+00:00 app[web.1]: {
2017-05-07T17:43:57.400844+00:00 app[web.1]:     "AudioPlayer": {
2017-05-07T17:43:57.400845+00:00 app[web.1]:       "playerActivity": "STOPPED"
2017-05-07T17:43:57.400845+00:00 app[web.1]:     },
2017-05-07T17:43:57.400846+00:00 app[web.1]:     "System": {
2017-05-07T17:43:57.400847+00:00 app[web.1]:       "apiEndpoint": "https://api.amazonalexa.com",
2017-05-07T17:43:57.400848+00:00 app[web.1]:       "application": {
2017-05-07T17:43:57.400849+00:00 app[web.1]:         "applicationId": "amzn1.ask.skill.bae3f4df-9358-42d4-9638-684560edd172"
2017-05-07T17:43:57.400849+00:00 app[web.1]:       },
2017-05-07T17:43:57.400850+00:00 app[web.1]:       "device": {
2017-05-07T17:43:57.400857+00:00 app[web.1]:         "deviceId": "amzn1.ask.device.B4RXNYDKAQ3RNNCEZLHIH5T4ZMT4PFM6CE2Q4ZJ4N3BXMFFWD4KNDTB32TPGGZR4QRFRZRVGC5RWKQTRPW7G3KC2ZP2B4ETTM5FOGUQCF4EXV53HZV3GTGJK7H6E2IRWNQHJ7Q",
2017-05-07T17:43:57.400858+00:00 app[web.1]:         "supportedInterfaces": {
2017-05-07T17:43:57.400859+00:00 app[web.1]:           "AudioPlayer": {}
2017-05-07T17:43:57.400864+00:00 app[web.1]:         "userId": "amzn1.ask.account.RB3PL33DEDOZLSS27OHMLGB5ZDQUYT37ZORHWA36UZ2TCVW5MLGKGEQIH3JMOWAH3AXIXNWRTGQ65EEHFS5NNZCHWAZCHTD7XROCO4N2PNSBFAY67AS5U2KKCD3LARRMFV5V7Q7U4IDCHQRWHM7LS7A2K54PWOWZQ7OFVGJTLIQ77J2RM6JNBYV7GI"
2017-05-07T17:43:57.400860+00:00 app[web.1]:       },
2017-05-07T17:43:57.400859+00:00 app[web.1]:         }
2017-05-07T17:43:57.400861+00:00 app[web.1]:       "user": {
2017-05-07T17:43:57.400865+00:00 app[web.1]:       }
2017-05-07T17:43:57.400866+00:00 app[web.1]:     }
2017-05-07T17:43:57.400866+00:00 app[web.1]:   },
2017-05-07T17:43:57.400867+00:00 app[web.1]:   "request": {
2017-05-07T17:43:57.400867+00:00 app[web.1]:     "intent": {
2017-05-07T17:43:57.400868+00:00 app[web.1]:       "confirmationStatus": "NONE",
2017-05-07T17:43:57.400869+00:00 app[web.1]:       "name": "GeeMusicPlayIFLRadioIntent"
2017-05-07T17:43:57.400869+00:00 app[web.1]:     },
2017-05-07T17:43:57.400870+00:00 app[web.1]:     "locale": "en-US",
2017-05-07T17:43:57.400870+00:00 app[web.1]:     "requestId": "amzn1.echo-api.request.ea7a5168-e7f6-474e-b274-4502b4de23c0",
2017-05-07T17:43:57.400871+00:00 app[web.1]:     "timestamp": "2017-05-07T17:43:57Z",
2017-05-07T17:43:57.400872+00:00 app[web.1]:     "type": "IntentRequest"
2017-05-07T17:43:57.400872+00:00 app[web.1]:   },
2017-05-07T17:43:57.400873+00:00 app[web.1]:   "session": {
2017-05-07T17:43:57.400873+00:00 app[web.1]:     "application": {
2017-05-07T17:43:57.400874+00:00 app[web.1]:       "applicationId": "amzn1.ask.skill.bae3f4df-9358-42d4-9638-684560edd172"
2017-05-07T17:43:57.400874+00:00 app[web.1]:     },
2017-05-07T17:43:57.400875+00:00 app[web.1]:     "new": true,
2017-05-07T17:43:57.400876+00:00 app[web.1]:     "sessionId": "amzn1.echo-api.session.33a542cd-6b7b-459a-9cff-72abfc2f9745",
2017-05-07T17:43:57.400876+00:00 app[web.1]:     "user": {
2017-05-07T17:43:57.400877+00:00 app[web.1]:       "userId": "amzn1.ask.account.B3PL33DEDOZLSS27OHMLGB5ZDQUYT37ZORHWA36UZ2TCVW5MLGKGEQIH3JMOWAH3AXIXNWRTGQ65EEHFS5NNZCHWAZCHTD7XROCO4N2PNSBFAY67AS5U2KKCD3LARRMFV5V7Q7U4IDCHQRWHM7LS7A2K54PWOWZQ7OFVGJTLIQ77J2RM6JNBYV7GI"
2017-05-07T17:43:57.400877+00:00 app[web.1]:     }
2017-05-07T17:43:57.400878+00:00 app[web.1]:   },
2017-05-07T17:43:57.400879+00:00 app[web.1]:   "version": "1.0"
2017-05-07T17:43:57.400921+00:00 app[web.1]: }
2017-05-07T17:43:57.401458+00:00 app[web.1]: {
2017-05-07T17:43:57.401459+00:00 app[web.1]:   "offsetInMilliseconds": 0,
2017-05-07T17:43:57.401460+00:00 app[web.1]:   "playerActivity": "STOPPED",
2017-05-07T17:43:57.401461+00:00 app[web.1]:   "token": "33826",
2017-05-07T17:43:57.401462+00:00 app[web.1]:   "url": "https://ccgmusic.herokuapp.com/alexa/stream/Tgmrl6gfrlrvta4jriy4qsm5jue"
2017-05-07T17:43:57.401481+00:00 app[web.1]: }
2017-05-07T17:44:00.279506+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-05-07T17:44:00.279503+00:00 app[web.1]: DEBUG in selection [/app/geemusic/intents/selection.py:179]:
2017-05-07T17:44:00.279491+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-05-07T17:44:00.279505+00:00 app[web.1]: stream_url = https://r6---sn-p5qs7nee.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=9f7825fa8311d6b5&itag=25&source=skyjam&begin=0&upn=q94ZkcR2UE4&ei=4FwPWdCMAYGD2QGhjouYCg&o=05645622889086387529&cmbypass=yes&ratebypass=yes&cpn=8Ol8uRA-8Q26kpXi8UBDbw&ip=54.226.106.34&ipbits=0&expire=1494179130&sparams=cmbypass,ei,expire,id,ip,ipbits,itag,mm,mn,ms,mv,o,pl,ratebypass,source,upn&signature=3CFB17AF9B4EA0C71A013203E5D077508893F86B.281A32355BC740C2FF91478E16560C32ECD2912E&key=cms1&mm=31&mn=sn-p5qs7nee&ms=au&mt=1494178946&mv=m&pl=15
2017-05-07T17:44:00.279966+00:00 app[web.1]:     "card": {
2017-05-07T17:44:00.279964+00:00 app[web.1]: {
2017-05-07T17:44:00.279965+00:00 app[web.1]:   "response": {
2017-05-07T17:44:00.279967+00:00 app[web.1]:       "image": {
2017-05-07T17:44:00.279968+00:00 app[web.1]:       },
2017-05-07T17:44:00.279968+00:00 app[web.1]:         "smallImageUrl": "https://i.imgur.com/NYTSqHZ.png"
2017-05-07T17:44:00.279969+00:00 app[web.1]:       "text": "",
2017-05-07T17:44:00.279970+00:00 app[web.1]:       "title": "Playing I'm Feeling Lucky Radio",
2017-05-07T17:44:00.279970+00:00 app[web.1]:       "type": "Standard"
2017-05-07T17:44:00.279967+00:00 app[web.1]:         "largeImageUrl": "https://i.imgur.com/NYTSqHZ.png",
2017-05-07T17:44:00.279972+00:00 app[web.1]:       {
2017-05-07T17:44:00.279971+00:00 app[web.1]:     },
2017-05-07T17:44:00.279973+00:00 app[web.1]:           "stream": {
2017-05-07T17:44:00.279971+00:00 app[web.1]:     "directives": [
2017-05-07T17:44:00.279974+00:00 app[web.1]:             "offsetInMilliseconds": 0,
2017-05-07T17:44:00.279973+00:00 app[web.1]:         "audioItem": {
2017-05-07T17:44:00.279975+00:00 app[web.1]:             "token": "82078",
2017-05-07T17:44:00.279976+00:00 app[web.1]:           }
2017-05-07T17:44:00.279975+00:00 app[web.1]:             "url": "https://ccgmusic.herokuapp.com/alexa/stream/Tawfx6x4tunbfviqmwrei6odyl4"
2017-05-07T17:44:00.279977+00:00 app[web.1]:         },
2017-05-07T17:44:00.279979+00:00 app[web.1]:       }
2017-05-07T17:44:00.279980+00:00 app[web.1]:     "outputSpeech": {
2017-05-07T17:44:00.279980+00:00 app[web.1]:       "text": "Playing music from your personalized station",
2017-05-07T17:44:00.279981+00:00 app[web.1]:       "type": "PlainText"
2017-05-07T17:44:00.279977+00:00 app[web.1]:         "playBehavior": "REPLACE_ALL",
2017-05-07T17:44:00.279978+00:00 app[web.1]:         "type": "AudioPlayer.Play"
2017-05-07T17:44:00.279981+00:00 app[web.1]:     },
2017-05-07T17:44:00.279979+00:00 app[web.1]:     ],
2017-05-07T17:44:00.279982+00:00 app[web.1]:     "shouldEndSession": true
2017-05-07T17:44:00.279983+00:00 app[web.1]:   },
2017-05-07T17:44:00.279984+00:00 app[web.1]: }
2017-05-07T17:44:00.279983+00:00 app[web.1]:   "sessionAttributes": {},
2017-05-07T17:44:00.279984+00:00 app[web.1]:   "version": "1.0"
2017-05-07T17:44:00.280314+00:00 app[web.1]: 10.169.124.243 - - [07/May/2017 17:44:00] "POST /alexa HTTP/1.1" 200 -
2017-05-07T17:44:01.962155+00:00 app[web.1]: {
2017-05-07T17:44:01.962168+00:00 app[web.1]:   "context": {
2017-05-07T17:44:01.962169+00:00 app[web.1]:     "AudioPlayer": {
2017-05-07T17:44:01.962170+00:00 app[web.1]:       "playerActivity": "STOPPED"
2017-05-07T17:44:01.962170+00:00 app[web.1]:     },
2017-05-07T17:44:01.962172+00:00 app[web.1]:       "apiEndpoint": "https://api.amazonalexa.com",
2017-05-07T17:44:01.962171+00:00 app[web.1]:     "System": {
2017-05-07T17:44:01.962173+00:00 app[web.1]:       "application": {
2017-05-07T17:44:01.962174+00:00 app[web.1]:         "applicationId": "amzn1.ask.skill.bae3f4df-9358-42d4-9638-684560edd172"
2017-05-07T17:44:01.962174+00:00 app[web.1]:       },
2017-05-07T17:44:01.962176+00:00 app[web.1]:         "deviceId": "amzn1.ask.device.Z3OMFCMB4RXNYDKAQ3RNNCEZLHIH5T4ZMT4PFM6CE2Q4ZJ4N3BXMFFWD4KNDTB32TPGGZR4QRFRZRVGC5RWKQTRPW7G3KC2ZP2B4ETTM5FOGUQCF4EXV53HZV3GTGJK7H6E2IRWNQHJ7Q",
2017-05-07T17:44:01.962176+00:00 app[web.1]:         "supportedInterfaces": {
2017-05-07T17:44:01.962177+00:00 app[web.1]:           "AudioPlayer": {}
2017-05-07T17:44:01.962178+00:00 app[web.1]:         }
2017-05-07T17:44:01.962178+00:00 app[web.1]:       },
2017-05-07T17:44:01.962179+00:00 app[web.1]:       "user": {
2017-05-07T17:44:01.962175+00:00 app[web.1]:       "device": {
2017-05-07T17:44:01.962180+00:00 app[web.1]:         "userId": "amzn1.ask.account.DOZLSS27OHMLGB5ZDQUYT37ZORHWA36UZ2TCVW5MLGKGEQIH3JMOWAH3AXIXNWRTGQ65EEHFS5NNZCHWAZCHTD7XROCO4N2PNSBFAY67AS5U2KKCD3LARRMFV5V7Q7U4IDCHQRWHM7LS7A2K54PWOWZQ7OFVGJTLIQ77J2RM6JNBYV7GI"
2017-05-07T17:44:01.962181+00:00 app[web.1]:       }
2017-05-07T17:44:01.962181+00:00 app[web.1]:     }
2017-05-07T17:44:01.962182+00:00 app[web.1]:   },
2017-05-07T17:44:01.962182+00:00 app[web.1]:   "request": {
2017-05-07T17:44:01.962183+00:00 app[web.1]:     "currentPlaybackState": {
2017-05-07T17:44:01.962184+00:00 app[web.1]:       "playerActivity": "STOPPED"
2017-05-07T17:44:01.962184+00:00 app[web.1]:     },
2017-05-07T17:44:01.962185+00:00 app[web.1]:     "error": {
2017-05-07T17:44:01.962186+00:00 app[web.1]:       "message": "Not Found, Response Code:404",
2017-05-07T17:44:01.962186+00:00 app[web.1]:       "type": "MEDIA_ERROR_INVALID_REQUEST"
2017-05-07T17:44:01.962187+00:00 app[web.1]:     },
2017-05-07T17:44:01.962187+00:00 app[web.1]:     "locale": "en-US",
2017-05-07T17:44:01.962189+00:00 app[web.1]:     "timestamp": "2017-05-07T17:44:01Z",
2017-05-07T17:44:01.962188+00:00 app[web.1]:     "requestId": "amzn1.echo-api.request.fc38dda9-9c74-42b7-b97a-5546c8b64bf7",
2017-05-07T17:44:01.962189+00:00 app[web.1]:     "token": "82078",
2017-05-07T17:44:01.962190+00:00 app[web.1]:     "type": "AudioPlayer.PlaybackFailed"
2017-05-07T17:44:01.962191+00:00 app[web.1]:   },
2017-05-07T17:44:01.962191+00:00 app[web.1]:   "version": "1.0"
2017-05-07T17:44:01.962760+00:00 app[web.1]: }
2017-05-07T17:44:01.963453+00:00 app[web.1]: {
2017-05-07T17:44:01.963455+00:00 app[web.1]:   "offsetInMilliseconds": 0,
2017-05-07T17:44:01.963456+00:00 app[web.1]:   "playerActivity": "STOPPED",
2017-05-07T17:44:01.963457+00:00 app[web.1]:   "url": "https://ccgmusic.herokuapp.com/alexa/stream/Tawfx6x4tunbfviqmwrei6odyl4"
2017-05-07T17:44:01.963487+00:00 app[web.1]: }
2017-05-07T17:44:01.963456+00:00 app[web.1]:   "token": "82078",
2017-05-07T17:44:01.964712+00:00 app[web.1]: 10.150.135.91 - - [07/May/2017 17:44:01] "POST /alexa HTTP/1.1" 400 -

**Comment by 2themaxx** [comment] 2017-05-07 18:13
Sorry, didn't mean to close the issue, it's still an open issue.

**Comment by pnimish** [comment] 2017-05-08 04:24
I am facing the same issue. This used to work fine a few days ago. I have made no code changes - it just stopped working.

**Comment by 2themaxx** [comment] 2018-01-11 04:40
Tried the latest version (late Dec 2017), and it now works. I had to regenerate the Intent and utterances for the model, but it works with the heroku instance.

**Comment by fergyfresh** [comment] 2018-06-18 17:29
Closing as of @2themaxx's comment on Jan 10.

**Closed by fergyfresh** 2018-06-18 17:29 UTC
