### ISSUE TITLE
"There was a problem with the requested skills response"

### ISSUE THREAD

**Issue by sheaandrew** [stevenleeg/geemusic#67] opened 2017-02-18 17:50 UTC
I'm having an issue where I believe both foreman and ngrok are both working properly, but whenever I I ask Alexa "Tell geemusic to play artist radiohead" I get "There was a problem with the requested skills response". This goes for almost any other request. Here's the output from the console. It looks likes there's a problem with flask, but I don't have much experience with it. Thank you in advance!

`17:39:04 web.1  | 127.0.0.1 - - [18/Feb/2017 17:39:04] "POST /alexa HTTP/1.1" 200 -
17:39:05 web.1  | 127.0.0.1 - - [18/Feb/2017 17:39:05] "POST /alexa HTTP/1.1" 500 -
17:39:05 web.1  | Traceback (most recent call last):
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
17:39:05 web.1  |     return self.wsgi_app(environ, start_response)
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
17:39:05 web.1  |     response = self.handle_exception(e)
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
17:39:05 web.1  |     reraise(exc_type, exc_value, tb)
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
17:39:05 web.1  |     response = self.full_dispatch_request()
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
17:39:05 web.1  |     rv = self.handle_user_exception(e)
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
17:39:05 web.1  |     reraise(exc_type, exc_value, tb)
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
17:39:05 web.1  |     rv = self.dispatch_request()
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
17:39:05 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 499, in _flask_view_func
17:39:05 web.1  |     self._update_stream()
17:39:05 web.1  |   File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 468, in _update_stream
17:39:05 web.1  |     fresh_stream.__dict__.update(self._from_context())
17:39:05 web.1  | TypeError: 'NoneType' object is not iterable

`

**Comment by PostsDesert** [comment] 2017-02-18 22:50
Have you tried this?

Music won't start playing
---------------
Issues where Alexa responds to your requests but doesn't play music are generally caused by the `APP_URL` environment variable being set improperly. Be sure that it is set to something like `APP_URL=https://ff9b5cce.ngrok.io` without a trailing slash or `/alexa`.

**Comment by sheaandrew** [comment] 2017-02-18 22:55
@PostsDesert Yup, that was the first thing I checked. I have a Canadian Google Play Music Account, which I hadn't considered to be the issue until you mentioned it. Do you think this could be the cause?

**Comment by PostsDesert** [comment] 2017-02-18 22:59
We've had some problems with non US accounts. Does telling geemusic `play songs from my library` work?

**Comment by sheaandrew** [comment] 2017-02-18 23:02
If I say "Tell geemusic to play songs from my library", I get "I couldn't find music in your library", and no POST appears, leading me to believe alexa is ignoring the "tell geemusic" and going straight to Amazon music. However, if I say "Open geemusic". pause, then say "play songs from my library" I get the original error " There was a problem with the requested skills response"

**Comment by PostsDesert** [comment] 2017-02-18 23:03
Does setting up the skill for a UK user work?

**Comment by sheaandrew** [comment] 2017-02-18 23:05
Good idea, I'll try that and report back.

**Comment by sheaandrew** [comment] 2017-02-19 17:47
OK, here's what I've tried so far:
1. Changed everything on the Amazon side to UK and updated URLs
2. Tried - didn't work
3. Changed ngrok region to EU and updated URLs
4. Tried - didn't work

Every time I ask Alexa to open gee music or a gee music command, she replies with "Sorry, I'm having trouble accessing your service right now". When I try the service simulator, I see the POST 200 on the foreman console and ngrok console without any errors (so better than using the US service). I've also confirmed that she is connected and other services are working properly.

**Comment by PostsDesert** [comment] 2017-02-20 00:45
Okay so I doubt this will work but you could try a fresh install using [this branch](https://github.com/PostsDesert/geemusic/tree/loop-support). Make sure to set you setting on the amazon side back to US or Canada.

**Comment by PostsDesert** [comment] 2017-07-18 01:08
Did that work? I believe those changes have been merged into master so a reinstall of geemusic would have the same effect.

**Comment by yurigit** [comment] 2018-01-14 10:29
Same issue for me.
My Amazon and Google accounts are US, but physically I'm in a different country.

All set up and running, Service Simulator returns a proper JSON response, streaming URL works in the browser.
But there's always "There's a problem with requested skill response" reply.

Master branch installed 2 days ago.

Thanks!

**Comment by stevenleeg** [comment] 2018-03-01 13:37
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.

**Closed by stevenleeg** 2018-03-01 13:37 UTC
