### ISSUE TITLE
Strange Account Activity

### ISSUE THREAD

**Issue by JoshuaGarrison27** [stevenleeg/geemusic#183] opened 2018-02-22 18:14 UTC
Hello everyone,

I have a odd issue that I didnt notice until recently when I started getting logged out of my google account about every day. Ive made a few changes and even renewed my api key for Geemusic.

I am just curious if anyone else is getting a lot of unknown "Android" devices in their Device Activity (https://myaccount.google.com/device-activity) view.

Ive reset my password, reset 2FA, removed old app access to my account, etc already. So at this point I am just desperately looking for some answers because Google cannot help me apparently.

I stopped my Heroku instance a few hours ago (around 10:40am) and I have not had a new device show up in the list. 

Does anyone else have this problem using Heroku and Geemusic?

Screenshot taken earlier just now
![2018-02-22 13_26_41-recently used devices](https://user-images.githubusercontent.com/1706923/36556759-40f8be00-17d4-11e8-8cae-b081137ccfb5.png)

**Comment by fergyfresh** [comment] 2018-02-22 19:58
I had that happen a few times a couple months ago. I was able to pin it down to if I had something playing in brower or on my phone and then signaled Alexa to play a song it would do it almost every time.

**Comment by stevenleeg** [comment] 2018-02-22 21:05
so long as you don't believe your account has actually been hijacked, I'm pretty sure this is a side-effect of using the unofficial [gmusicapi](https://github.com/simon-weber/gmusicapi).

**Comment by JoshuaGarrison27** [comment] 2018-02-22 21:28
That's what I was thinking. Have you also seen this before @stevenleeg?

**Comment by simon-weber** [comment] 2018-02-22 21:47
Ah, yeah, that's probably expected when using FROM_MAC_ADDRESS on a platform like heroku: since you don't have a stable mac, each new dyno has probably been creating a new device.

Looking at geemusic, setting ANDROID_ID in the env should stop it from happening.

**Comment by stevenleeg** [comment] 2018-02-22 21:51
^ that's from the gmusicapi maintainer himself.

since this is expected behavior I'm going to go ahead and close this issue, but feel free to re-open if there's more to discuss.

**Closed by stevenleeg** 2018-02-22 21:51 UTC

**Comment by JoshuaGarrison27** [comment] 2018-02-22 21:57
I will try that! Thanks. I assume that works in geemusic as kind of a bubble up effect from the GMusicapi library. Correct me if I'm wrong. 

Thanks everyone!

**Comment by simon-weber** [comment] 2018-02-22 22:00
Sure thing.

To clarify, the env var is geemusic-specific. I found it here: https://github.com/stevenleeg/geemusic/blob/b5717c0020b521864d73fec6d408ce520f574984/geemusic/utils/music.py#L14

I should probably emphasize in the gmusicapi docs that FROM_MAC_ADDRESS is kind of fraught. I've seen this kind of thing happen a few time on other similar platforms (like vms, which often randomize mac on startup).

**Comment by JoshuaGarrison27** [comment] 2018-02-22 22:16
Fantastic! Thanks for the explanation Simon. It is much appreciated!
