### ISSUE TITLE
Skips to next song in queue halfway through

### ISSUE THREAD

**Issue by chasedixon** [stevenleeg/geemusic#234] opened 2018-06-20 18:51 UTC
When playing from one of my playlists, it plays each song for a minute or two, then pauses and skips to the next song. As far as I can tell it happens with every song on every playlist. I haven't timed it to see if it is a consistent length of time or not. Is anyone else having this issue?

**Comment by JonathanPicques** [comment] 2018-07-05 11:50
Yeah same happens to me, if there is no next song, the play just abruptly stops

**Comment by JackED42** [comment] 2018-07-08 14:31
Yep, I have the same issue too, any ideas?

**Comment by fergyfresh** [comment] 2018-07-09 15:35
I'm going to need some information from you guys about what you use when you see these symptoms. First do you use the free version or the payed version of Google Play Music. Secondly, do you play your own playlist or a curated playlist? Lastly, how do you think that I could reproduce this bug that you're seeing? I typically use `Play top tracks by { artist }`, `Play some music`, and `Play songs like this`, so I have never tried to use the same utterances as you guys. 

Let me know, I'd love to clean up this issue as there are others with the same issue. I'm going to back link them all to this and close them and keep this one open for simplicities sake since you're the most active thread as of right now.

**Comment by chasedixon** [comment] 2018-07-10 03:58
I'm using the paid version and it's been on my created playlists. I usually just say "Tell GeeMusic to play my {playlist} playlist"

**Comment by chasedixon** [comment] 2018-07-10 04:03
It looks like it's only on my created playlists. The commands you mentioned seem to work just fine.

**Comment by fergyfresh** [comment] 2018-07-10 13:08
Can you try to reproduce it with the `gmusicapi` when you get a chance? I'm not sold on it being a problem with us as its just streaming from the URL returned from google. I'm not sure though I'd have to play around with it first.

**Comment by chasedixon** [comment] 2018-07-10 18:19
Alright, not sure what happened. But it seems to be working great now.. Anyone still seeing the issue?

**Comment by fergyfresh** [comment] 2018-07-10 19:08
It seemed to work basically the same way as the `Play some music` intent where it queues up all the songs that are returned by the `gmusicapi.MobileClient` so that's why I was so perplexed. I don't have any personal playlists, but ill make one right now and verify when I get home that it plays through properly. I know that if I use my phone and the Alexa app at the same time it will pause if I play on my phone. So maybe this is the symptoms you're seeing?

**Comment by fergyfresh** [comment] 2018-07-11 16:59
@chasedixon works for mee too. Comment on this issue if you see it again, otherwise I'm gonna close it.

**Closed** 2018-07-11 16:59 UTC

**Comment by JackED42** [comment] 2018-07-14 08:14
Hi.

I am still getting this issue. It is happening every song on my own personal playlist.

It is on paid Google play music.

The command is "Start playlist <Playlist name>"

Sorry for delayed answer

**Comment by fergyfresh** [comment] 2019-01-16 15:17
Are you getting logged out?

**Comment by fergyfresh** [comment] 2019-01-16 15:18
This is so weird, i don't get this issue.

**Comment by jznomoney** [comment] 2019-01-16 23:34
I don't think so.  Is there a way to find out?

**Comment by fergyfresh** [comment] 2019-01-18 16:40
Check the server logs and post them here.

**Comment by jznomoney** [comment] 2019-01-26 15:40
here are the server logs @fergyfresh https://pastebin.com/wu98zc8v

**Comment by fergyfresh** [comment] 2019-01-29 20:34
Seems to be working fine as far as I can tell. You see anything wonky?

**Comment by fergyfresh** [comment] 2019-01-29 20:34
what timestamps do you think are the problem?

**Comment by jznomoney** [comment] 2019-05-03 16:34
just a follow up on this.  I have two other amazon echo device one is an Amazon Echo (2nd Generation) the other two are Echo Dot (3rd Generation).  Only one of my 3rd gen stops like I stated before.  The other two devices work fine.  I tried resetting the one that isn't finishing right and it still doesn't go to the end.  Am I missing something?
